config/routes.rb
Rails.application.routes.draw do
    get "homes/index"
    root 'homes#index'
    resources :meal_plans, only: [:index, :show, :new, :create]
    resources :meal_restrictions, only: [:index, :show, :new, :create]
    resources :meals, only: [:index, :show, :new, :create, :edit, :update]
    resources :mp_meals, only: [:index, :new, :create]
    resources :restrictions, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ActiveRecord

end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :mpmeals
  has_many :mealrestrictions
  has_many :mealplans, through: :mpmeals
  has_many :restrictions, through: :mealrestrictions
  accepts_nested_attributes_for :restrictions, :mealrestrictions

  def assign_restrictions(meal_id, rest_arr)
   rest_arr.each do |rest|
     id = rest.to_i
     MealRestriction.create(meal_id: meal_id, restriction_id: id)
   end
 end
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  has_many :mp_meals
  has_many :meals, through: :mp_meals
  accepts_nested_attributes_for :meals, :mp_meals
end

app/models/meal_restriction.rb
class MealRestriction < ApplicationRecord
  belongs_to :meal
  belongs_to :restriction
  # accepts_nested_attributes_for :meals, :restrictions
end

app/models/meal_restrictions.rb
class MealRestriction < ApplicationRecord
  belongs_to :meal
  belongs_to :restriction
  # accepts_nested_attributes_for :meals, :restrictions
end

app/models/mp_meal.rb
class MpMeal < ApplicationRecord
  belongs_to :meal_plan
  belongs_to :meal
  accepts_nested_attributes_for :meal_plan, :meal

end

app/models/restriction.rb
class Restriction < ApplicationRecord
  has_many :mealrestrictions
  has_many :meals, through: :mealrestrictions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  def index
    @mealplans = MealPlan.all
  end

  def show
    @mealplan = MealPlan.find(params[:id])
  end

  def new
    @mealplan = MealPlan.new
  end

  def create
    @mealplan = MealPlan.create(strong_params)
    @mealplan.save
    redirect_to meal_plan_path(@mealplan)
  end

  private

  def strong_params
    params.require(:meal_plan).permit(
      :name,
      :meal_id
    )
  end
end

app/controllers/meal_restrictions_controller.rb
class MealRestrictionsController < ApplicationController
  def index
    @mealrestrictions = MealRestriction.all
  end

  def new
    @mealrestriction = MealRestriction.new
  end

  def create
    @mealrestriction = MealRestriction.create(:meal_id, :restriction_id)
    @mealrestriction.save
  end

 #  def assign_restrictions(meal_id, rest_arr)
 #   rest_arr.each do |rest|
 #     id = rest.to_i
 #     # byebug
 #     MealRestriction.create
 #   end
 # end

  # private
  #
  # def strong_params
  #   params.require(:mealrestriction).permit(
  #     :meal_id,
  #     :restriction_id
  #   )
  # end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.create(name: strong_params[:name])
    rest_arr = strong_params[:id].reject! {|e| e.empty?}
    @meal.assign_restrictions(@meal.id, rest_arr)
    @meal.save
    redirect_to meal_path(@meal)
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def update
    @meal = Meal.find(params[:id])
    @meal.update(name: params[:meal][:name])
    rest_arr = strong_params[:id].reject! {|e| e.empty?}
    @meal.assign_restrictions(@meal.id, rest_arr)
    redirect_to meal_path(@meal)
  end

  private

  def strong_params
    params.require(:meal).permit(
      :name, id: []
    )
  end
end

app/controllers/mp_meals_controller.rb
class MpMealsController < ApplicationController
  def index
    @mpmeals = MpMeal.all
  end

  def new
    @mpmeal = MpMeal.new
  end

  def create
    @mpmeal = MpMeal.create(strong_params)
    @mpmeal.save
  end

  private

  def strong_params
    params.require(:mp_meal).permit(
      :mp_id, :meal_id
    )
  end
end

app/controllers/restrictions_controller.rb
class RestrictionsController < ApplicationController
  def index
    @restrictions = Restriction.all
  end

  def show
    @restriction = Restriction.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/helpers/meal_restrictions_helper.rb
module MealRestrictionsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/mp_meals_helper.rb
module MpMealsHelper
end

app/helpers/restrictions_helper.rb
module RestrictionsHelper
end

app/views/homes/index.html.erb
<h1>The Thoughtful Eater</h1>

<h4>~ Meal Planning Made Easy ~</h4>
<br>
<br>
<a href="http://localhost:3000/meals/">Meals</a>
<br><br>
<a href="http://localhost:3000/meals/new">Create a New Meal</a>
<br><br>
<a href="http://localhost:3000/restrictions/">Dietary Restriction Info</a>

app/views/meal_plans/index.html.erb
<h1>Meal Plans</h1>
<% MealPlan.all.each do |mp|%>
<ul>
  <li><%=link_to "#{mp.name.capitalize}", mp%></li>
</ul>
<% end %>

<%= link_to 'Back', :back %>

app/views/meal_plans/new.html.erb
<h1>Create New Meal Plan</h1>
<%= form_for(@mealplan) do |f|%><br>

<%=f.label "Enter Meal Plan Name"%>
<%=f.text_field :name%><br><br>


<%=f.label "Monday"%><br><br>
<%=f.label "Breakfast"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%>
<%=f.label "Lunch"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%>
<%=f.label "Dinner"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%><br><br>


<%=f.label "Tuesday"%><br><br>
<%=f.label "Breakfast"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%>
<%=f.label "Lunch"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%>
<%=f.label "Dinner"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%><br><br>


<%=f.label "Wednesday"%><br><br>
<%=f.label "Breakfast"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%>
<%=f.label "Lunch"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%>
<%=f.label "Dinner"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%><br><br>


<%=f.label "Thursday"%><br><br>
<%=f.label "Breakfast"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%>
<%=f.label "Lunch"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%>
<%=f.label "Dinner"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%><br><br>


<%=f.label "Friday"%><br><br>
<%=f.label "Breakfast"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%>
<%=f.label "Lunch"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%>
<%=f.label "Dinner"%>
<%=f.collection_select(:id, Meal.all, :id, :name)%><br><br>


<%=f.submit "Create Meal Plan" %>
<%end%>

<%= link_to 'Back', :back %>

app/views/meal_plans/show.html.erb
<h1><%=@mealplan.name.capitalize%></h1>
<br>
<h2>All Meals in This Plan:</h2>
<ul>
  <% MpMeal.all.each do |mpm| %>
  <% if mpm.mp_id == @mealplan.id%>
  <% Meal.all.each do |m| %>
  <% if m.id == mpm.meal_id%>
    <li><%=link_to "#{m.name.capitalize}", m %></li>
  <% end %>
  <%end %>
  <%end %>
  <%end %>
</ul>

<%= link_to 'Back', :back %>

<!-- This should work in theory!!! -->

app/views/meal_restrictions/edit.html.erb
<h1>Edit the Restriction: <%=@restriction.name%></h1>
<%= %>
<%= %>
<%= %>
<%= %>
<%= %>
<%= %>

app/views/meals/edit.html.erb
<h1>Edit this Meal: </h1>

<%=form_for @meal do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <br>
  <br>
  <ul>
  <%= f.label "Safe For: " %>
    <% MealRestriction.all.each do |mr| %>
    <% if mr.meal_id == @meal.id %>
    <% Restriction.all.each do |rest| %>
    <% if rest.id == mr.restriction_id %>
    <li><%= rest.name %></li>
    <% end %>
    <% end %>
    <% end %>
    <% end %>
  </ul>

  <%= f.label "Add: " %>
  <br>
  <%= f.collection_select(:id, Restriction.all, :id, :name, {:prompt => "Please choose as many that apply"}, {:multiple => true}) %>

  <br>
  <br>

  <%= f.submit "Submit Changes"%>
<% end %>

<br>
<br>

<%= link_to 'Home', root_path %>
<%= link_to 'All Meals', meals_path %>
<%= link_to 'All Restrictions', restrictions_path %>
<%= link_to 'Back', :back %>

app/views/meals/index.html.erb
<ul>
  <h1>Meals</h1>
<% Meal.all.each do |meal|%>
  <li><%=link_to "#{meal.name.capitalize}", meal_path(meal)%></li>
<%end%>
</ul>
<%= link_to new_meal_path do %>New Meal<% end %>
<br>

<div class="nav_links">
<%= link_to 'Home', root_path %>
<%= link_to 'All Meals', meals_path %>
<%= link_to 'All Restrictions', restrictions_path %>
<%= link_to 'Back', :back %>
</div>

app/views/meals/new.html.erb
<h1>Create new meal</h1>
<%= form_for(@meal) do |f|%>
<h3><%=f.label :name%> </h3>
<%=f.text_field :name%>
<h3><%=f.label "Safe for the following food restrictions:"%><br></h3>
<%= f.label "hold command to choose multiple" %><br>

<%= f.collection_select(:id, Restriction.all, :id, :name, {:prompt => "Please choose as many that apply"}, {:multiple => true}) %><br>
<br>
<%=f.submit "Save meal" %><br>
<% end%>
<br>
<%= link_to 'Home', root_path %>
<%= link_to 'All Meals', meals_path %>
<%= link_to 'All Restrictions', restrictions_path %>
<%= link_to 'Back', :back %>

app/views/meals/show.html.erb
<ul>
<h1><%=@meal.name.capitalize%></h1>
<br>
<h2>Safe for:</h2>
  <%MealRestriction.all.each do |mr|%>
  <% if mr.meal_id == @meal.id %>
  <%Restriction.all.each do |rest|%>
  <% if rest.id == mr.restriction_id%>
  <li><%=link_to "#{rest.name.capitalize}", restriction_path(rest) %></li>
  <%end %>
  <%end %>
<%end %>
<%end %>
</ul>
<%= link_to edit_meal_path(@meal) do %>Edit Meal<% end %>
<br>
<%= link_to 'Home', root_path %>
<%= link_to 'All Meals', meals_path %>
<%= link_to 'All Restrictions', restrictions_path %>
<%= link_to 'Back', :back %>

app/views/mp_meals/index.html.erb
<h1>Meal Plan Meals</h1>

app/views/restrictions/index.html.erb
<div class="jumbotron">

<h1>Restrictions</h1>
<% Restriction.all.each do |restriction|%>
<ul>
  <li><%=link_to "#{restriction.name.capitalize}", restriction_path(restriction)%></li>
</ul>
<%end%>
<br>
<%= link_to 'Home', root_path %>
<%= link_to 'All Meals', meals_path %>
<%= link_to 'All Restrictions', restrictions_path %>
<%= link_to 'Back', :back %>
</div>

app/views/restrictions/show.html.erb
<ul>
  <h1><%=@restriction.name.capitalize%></h1>

  <p><%= @restriction.description %></p>
  <br>
  <%MealRestriction.all.each do |mr|%>
  <% if mr.restriction_id == @restriction.id %>
  <% Meal.all.each do |m|%>
  <% if m.id == mr.meal_id%>
  <li><%= link_to "#{m.name.capitalize}", meal_path(m)%></li>
  <%end %>
  <%end %>
  <%end %>
  <%end %>
</ul>
<br>
<%= link_to 'Home', root_path %>
<%= link_to 'All Meals', meals_path %>
<%= link_to 'All Restrictions', restrictions_path %>
<%= link_to 'Back', :back %>